"""empty message

Revision ID: 2f553b52d53b
Revises: fd7f3b1aaba6
Create Date: 2020-07-21 14:21:02.925343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f553b52d53b'
down_revision = 'fd7f3b1aaba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('badge_number', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('officer_name', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('zip_code', sa.String(), nullable=True))
    op.drop_column('reports', 'createdDate')
    op.drop_column('reports', 'officerName')
    op.drop_column('reports', 'badgeNum')
    op.drop_column('reports', 'zipCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('zipCode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('badgeNum', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('officerName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('createdDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'zip_code')
    op.drop_column('reports', 'officer_name')
    op.drop_column('reports', 'created_date')
    op.drop_column('reports', 'badge_number')
    # ### end Alembic commands ###
