"""empty message

Revision ID: fa39f899451b
Revises: daca186d1f35
Create Date: 2020-07-22 15:16:57.239440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa39f899451b'
down_revision = 'daca186d1f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('created_date', sa.String(), nullable=True))
    op.drop_column('reports', 'createdDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('createdDate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'created_date')
    # ### end Alembic commands ###
