"""empty message

Revision ID: fd7f3b1aaba6
Revises: 8107e8fc0b2f
Create Date: 2020-07-21 13:37:59.635965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd7f3b1aaba6'
down_revision = '8107e8fc0b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('badgeNum', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('createdDate', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('officerName', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('parties', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('zipCode', sa.String(), nullable=True))
    op.drop_column('reports', 'zip_code')
    op.drop_column('reports', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'zipCode')
    op.drop_column('reports', 'parties')
    op.drop_column('reports', 'officerName')
    op.drop_column('reports', 'createdDate')
    op.drop_column('reports', 'badgeNum')
    # ### end Alembic commands ###
